#!/usr/bin/python3

import subprocess
import cgi


import os
from twilio.rest import Client

# Set environment variables for your credentials
# Read more at http://twil.io/secure
account_sid = "account_id"
auth_token = "auth_token"
verify_sid = "verified_number"
verified_number = "+9197XXXXXXX"

client = Client(account_sid, auth_token)

verification = client.verify.v2.services(verify_sid) \
  .verifications \
  .create(to=verified_number, channel="sms")
print(verification.status)


